/** @format */

import type { Metadata } from 'next'
import { Noto_Sans_SC } from 'next/font/google'
import './globals.css'
import ThemeProvider from '@/app/_components/ThemePrivider'
import { AntdRegistry } from '@ant-design/nextjs-registry'

const notoSansSC = Noto_Sans_SC({
  variable: '--font-sans',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='zh-CN'
      className={`${notoSansSC.variable} antialiased`}>
      <body className='relative w-screen h-screen flex overflow-hidden bg-background text-foreground'>
        <AntdRegistry>
          <ThemeProvider>{children}</ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  )
}
