/** @format */

import type { Metadata } from 'next'
import { Noto_Sans_SC } from 'next/font/google'
import '../ui/globals.css'
import ThemeProvider from '@/ui/ThemePrivider'

const notoSansSC = Noto_Sans_SC({
  variable: '--font-sans',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='zh-CN'
      className={`${notoSansSC.variable} antialiased`}>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
